#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

new_s="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $new_s" /etc/nginx/sites-available/default

new_s="error_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /var/www/html/404.html;\n\t\tinternal;}\n"
sudo sed -i "/server_name _;/a $new_s" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart
