#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

new_s="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $new_s" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_s="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot    /var/www/html/;\n\t\tinternal;\n\t\t}\n"
sudo sed -i "/server_name _;/a $new_s" /etc/nginx/sites-available/default

head="add_header X-Served-By $HOSTNAME;"
sudo sed -i "/server_name _;/a $head" /etc/nginx/sites-available/default

sudo service nginx restart
