#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6 -y
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*

sudo echo ENABLED=1 | sudo tee /etc/default/haproxy
sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
bind *:80
mode http
default_backend web_backend

backend web_backend
balance roundrobin
server 1298-web-01 34.75.57.54:80 check
server 1298-web-02 34.74.149.81:80 check
EOF
sudo service haproxy restart
