#!/usr/bin/env bash
#Debugging

sudo service nginx restart
cd /etc/nginx/sites-enabled
sudo rm default
sudo ln -s /etc/nginx/sites-available/default default
sudo sed -i "s/8080/80" /etc/nginx/sites-available/default
sudo service nginx restart
