#!/usr/bin/env bash
# This script that displays Holberton School 10 times.

i=1
while [ $i -lt 10 ]
do
    echo 'Holberton School'
    if [ $i -eq 8 ]
    then
	echo 'Hi'
    fi
    i=$((i + 1))
done
