#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations

i=1
while [ $i -le 20 ]
do
    case $i in
	5)
	echo 'bad luck from China';;
	10)
	echo 'bad luck from Japan';;
	18)
	echo 'bad luck from Italy';;
	*) ;;
    esac
    echo $i
    i=$(( $i + 1 ))
done
