#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations

i=0
while [ $i -le 11 ]
do
    echo 'Hour: '$i
    for j in {1..59}
    do
	echo "$j"
    done
    i=$(( i + 1 ))
done
