#!/usr/bin/env bash
# Run Nginx as Nginx

pkill apache2
change="#user www-data;"
new="user nginx;"
sed -i "s/$change/$new/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
